# Generated by Django 5.0 on 2024-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("title_detail", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=30)),
                ("price_detail", models.CharField(max_length=30)),
                ("benefit_1", models.CharField(max_length=30)),
                ("benefit_2", models.CharField(max_length=30)),
                ("benefit_3", models.CharField(max_length=30)),
                ("benefit_4", models.CharField(max_length=30)),
                ("benefit_5", models.CharField(max_length=30)),
                ("benefit_6", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
