# Generated by Django 5.0 on 2024-01-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="benefit_1",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_2",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_3",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_4",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_5",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_6",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="price_detail",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="title_detail",
            field=models.CharField(max_length=50),
        ),
    ]
