# Generated by Django 5.0 on 2024-01-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0002_alter_card_benefit_1_alter_card_benefit_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="benefit_1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_3",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_4",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_5",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="benefit_6",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
