# Generated by Django 5.0 on 2024-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0005_alter_card_benefit_2_alter_card_benefit_3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="period",
            field=models.IntegerField(null=True),
        ),
    ]
