# Generated by Django 5.0 on 2024-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0006_card_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="period",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.IntegerField(),
        ),
    ]
