# Generated by Django 5.0 on 2024-02-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0007_alter_card_period_alter_card_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="display_price",
            field=models.IntegerField(null=True),
        ),
    ]
