# Generated by Django 5.0 on 2024-02-14 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("zumba", "Zumba"),
                            ("cycling", "Cycling"),
                            ("bodypump", "Bodypump"),
                            ("aerobic", "Aerobic"),
                            ("trx", "Trx"),
                            ("crossfit", "Crossfit"),
                        ],
                        max_length=8,
                    ),
                ),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                ("people_nr", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
