# Generated by Django 5.0 on 2024-02-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0001_initial"),
        ("member", "0005_alter_member_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("crossfit", "TRAINING"),
                    ("aerobic", "AEROBIC"),
                    ("zumba", "ZUMBA"),
                    ("bodypump", "BODYPUMP"),
                    ("trx", "TRX"),
                    ("cycling", "CYCLING"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="classgym",
            name="trainer",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="member.member",
            ),
        ),
    ]
