# Generated by Django 5.0 on 2024-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0002_alter_classgym_title_alter_classgym_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("trx", "TRX"),
                    ("aerobic", "AEROBIC"),
                    ("bodypump", "BODYPUMP"),
                    ("cycling", "CYCLING"),
                    ("crossfit", "TRAINING"),
                    ("zumba", "ZUMBA"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="classgym",
            name="trainer",
            field=models.CharField(
                choices=[
                    ("trx", "TRX"),
                    ("aerobic", "AEROBIC"),
                    ("bodypump", "BODYPUMP"),
                    ("cycling", "CYCLING"),
                    ("crossfit", "TRAINING"),
                    ("zumba", "ZUMBA"),
                ],
                max_length=8,
            ),
        ),
    ]
