# Generated by Django 5.0 on 2024-02-01 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0004_alter_classgym_title_alter_classgym_trainer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("cycling", "CYCLING"),
                    ("bodypump", "BODYPUMP"),
                    ("aerobic", "AEROBIC"),
                    ("zumba", "ZUMBA"),
                    ("crossfit", "TRAINING"),
                    ("trx", "TRX"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="classgym",
            name="trainer",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
