# Generated by Django 5.0 on 2024-02-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0005_alter_classgym_title_alter_classgym_trainer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("aerobic", "AEROBIC"),
                    ("cycling", "CYCLING"),
                    ("crossfit", "TRAINING"),
                    ("bodypump", "BODYPUMP"),
                    ("zumba", "ZUMBA"),
                    ("trx", "TRX"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="classgym",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
