# Generated by Django 5.0 on 2024-02-03 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0007_alter_classgym_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("crossfit", "CROSSFIT"),
                    ("zumba", "ZUMBA"),
                    ("bodypump", "BODYPUMP"),
                    ("aerobic", "AEROBIC"),
                    ("trx", "TRX"),
                    ("cycling", "CYCLING"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="classgym",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
