# Generated by Django 5.0 on 2024-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0012_rename_trainer_classgym_user_alter_classgym_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classgym",
            old_name="user",
            new_name="trainer",
        ),
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("zumba", "ZUMBA"),
                    ("trx", "TRX"),
                    ("bodypump", "BODYPUMP"),
                    ("aerobic", "AEROBIC"),
                    ("crossfit", "CROSSFIT"),
                    ("cycling", "CYCLING"),
                ],
                max_length=8,
            ),
        ),
    ]
