# Generated by Django 5.0 on 2024-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0034_alter_classgym_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgym",
            name="title",
            field=models.CharField(
                choices=[
                    ("zumba", "Zumba"),
                    ("cycling", "Cycling"),
                    ("crossfit", "Crossfit"),
                    ("aerobic", "Aerobic"),
                    ("trx", "Trx"),
                    ("bodypump", "Bodypump"),
                ],
                max_length=8,
            ),
        ),
    ]
