# Generated by Django 5.0 on 2024-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
