# Generated by Django 5.0 on 2024-01-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_member_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.IntegerField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
