# Generated by Django 5.0 on 2024-01-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0004_member_birth_date_alter_member_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
