# Generated by Django 5.0 on 2024-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_class",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="time_class",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="title_class",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="trainer_class",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
