# Generated by Django 5.0 on 2024-02-06 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0005_userclass_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserClass",
        ),
    ]
