# Generated by Django 5.0 on 2024-02-06 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0008_remove_userclass_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserClass",
        ),
    ]
