# Generated by Django 5.0 on 2024-02-06 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0010_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClassUser",
        ),
    ]
