# Generated by Django 5.0 on 2024-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0013_alter_userclass_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclass",
            name="joined_classes",
        ),
        migrations.AddField(
            model_name="userclass",
            name="joined_classes",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
