# Generated by Django 5.0 on 2024-02-06 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0014_remove_userclass_joined_classes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserClass",
        ),
    ]
