# Generated by Django 5.0 on 2024-02-06 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0016_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Program",
        ),
    ]
