# Generated by Django 5.0 on 2024-02-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_schedule", "0034_alter_classgym_title"),
        ("userextend", "0018_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userschedule",
            name="joined_classes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="class_schedule.classgym",
            ),
        ),
    ]
