# Generated by Django 5.0 on 2024-02-07 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0008_card_display_price"),
        ("userextend", "0020_usersubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="subscription",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="prices.card"
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
