# Generated by Django 5.0 on 2024-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0021_alter_usersubscription_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="card_number",
            field=models.CharField(max_length=15),
        ),
    ]
