# Generated by Django 5.0 on 2024-02-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0022_alter_usersubscription_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="card_number",
            field=models.CharField(max_length=4),
        ),
    ]
